#pragma once

#include <QMainWindow>
#include <QApplication>
#include <QGraphicsView>
#include <QPushButton>
#include <QGraphicsScene>
#include <QGraphicsEllipseItem>
#include <QPen>
#include <QTextEdit>
#include <QBrush>
#include <QColor>
#include <QDialog>
#include <QtGui>
#include <QKeyEvent>
#include <QInputDialog>
#include <QImage>
#include <QAbstractAnimation>
#include <QAnimationGroup>
#include <QString>
#include <QErrorMessage>
#include <QAbstractItemView>
#include <QPropertyAnimation>
#include <QTimer>
#include <QPoint>
#include <QFont>
#include <random>
#include <ctime>
#include <iostream>
#include <unordered_set>
#include <QLabel>
#include <cmath>
#include <vector>
#include <set>
#include <random>
#include <chrono>
#include <QMessageBox>
